In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('adult.txt', header=None)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
16,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
22,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
32532,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
32533,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
32534,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K
32535,22,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K
32536,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
32537,30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,<=50K
32538,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32540,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
32541,41,?,202822,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,<=50K
32542,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K
32543,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
32544,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K
32545,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
32546,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32547,43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
32548,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
32549,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
32550,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32551,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
32552,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32555,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [3]:
df = pd.get_dummies(df, columns = [1, 3, 5, 6, 7, 8, 9, 13, 14], drop_first=True)
df

,0,2,4,10,11,12,1_ Federal-gov,1_ Local-gov,1_ Never-worked,1_ Private,...,13_ Puerto-Rico,13_ Scotland,13_ South,13_ Taiwan,13_ Thailand,13_ Trinadad&Tobago,13_ United-States,13_ Vietnam,13_ Yugoslavia,14_ >50K
0,39,77516,13,2174,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,50,83311,13,0,0,13,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,38,215646,9,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
3,53,234721,7,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
4,28,338409,13,0,0,40,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5,37,284582,14,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
6,49,160187,5,0,0,16,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7,52,209642,9,0,0,45,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
8,31,45781,14,14084,0,50,0,0,0,1,...,0,0,0,0,0,0,1,0,0,1
9,42,159449,13,5178,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,1
10,37,280464,10,0,0,80,0,0,0,1,...,0,0,0,0,0,0,1,0,0,1
11,30,141297,13,0,0,40,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
12,23,122272,13,0,0,30,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
13,32,205019,12,0,0,50,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
14,40,121772,11,0,0,40,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
15,34,245487,4,0,0,45,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
16,25,176756,9,0,0,35,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
17,32,186824,9,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
18,38,28887,7,0,0,50,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
19,43,292175,14,0,0,45,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
20,40,193524,16,0,0,60,0,0,0,1,...,0,0,0,0,0,0,1,0,0,1
21,54,302146,9,0,0,20,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
22,35,76845,5,0,0,40,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
23,43,117037,7,0,2042,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
24,59,109015,9,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
25,56,216851,13,0,0,40,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
26,19,168294,9,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
27,54,180211,10,0,0,60,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
28,39,367260,9,0,0,80,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
29,49,193366,9,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,33811,13,0,0,99,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32532,34,204461,16,0,0,60,0,0,0,1,...,0,0,0,0,0,0,1,0,0,1
32533,54,337992,13,0,0,50,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
32534,37,179137,10,0,0,39,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32535,22,325033,8,0,0,35,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32536,34,160216,13,0,0,55,0,0,0,1,...,0,0,0,0,0,0,1,0,0,1
32537,30,345898,9,0,0,46,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32538,38,139180,13,15020,0,45,0,0,0,1,...,0,0,0,0,0,0,1,0,0,1
32539,71,287372,16,0,0,10,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
32540,45,252208,9,0,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32541,41,202822,9,0,0,32,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32542,72,129912,9,0,0,25,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32543,45,119199,12,0,0,48,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
32544,31,199655,14,0,0,30,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32545,39,111499,12,0,0,20,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
32546,37,198216,12,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32547,43,260761,9,0,0,40,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
32548,65,99359,15,1086,0,60,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32549,43,255835,10,0,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32550,43,27242,10,0,0,50,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32551,32,34066,6,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32552,43,84661,11,0,0,45,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32553,32,116138,14,0,0,11,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
32554,53,321865,14,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,1
32555,22,310152,10,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32556,27,257302,12,0,0,38,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32557,40,154374,9,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,1
32558,58,151910,9,0,0,40,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32559,22,201490,9,0,0,20,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
32560,52,287927,9,15024,0,40,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1

In [4]:
X = df.values[:,:-1]
y = df.values[:,-1]

In [5]:
# Question 1:
# hard voting classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
log_clf = LogisticRegression(solver='lbfgs')
rnd_clf = RandomForestClassifier(n_estimators=100)
svm_clf = SVC(gamma='scale')
voting_clf = VotingClassifier(
    estimators=[('lr', log_clf), ('rf', rnd_clf), ('svc', svm_clf)],
    voting='hard')

In [7]:
# measure the algorithm performance using 10-fold cross validation
from sklearn.model_selection import cross_val_score
for clf in (log_clf, rnd_clf, svm_clf, voting_clf):
    hard_voting_score = cross_val_score(voting_clf, X, y, scoring = 'accuracy', cv=10)
    print(clf.__class__.__name__, hard_voting_score.mean())

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)

LogisticRegression [0.80933374 0.81265356 0.80835381 0.81265356 0.81081081 0.81910319
 0.8034398  0.81449631 0.81234644 0.81971744]

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)

RandomForestClassifier [0.80964077 0.81234644 0.80743243 0.81265356 0.81111794 0.81848894
 0.80436118 0.81541769 0.81142506 0.82002457]

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)

SVC [0.80933374 0.81296069 0.80804668 0.81296069 0.81173219 0.81879607
 0.80282555 0.81511057 0.81234644 0.8203317 ]

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)

VotingClassifier [0.80902671 0.81265356 0.80743243 0.81265356 0.81142506 0.81910319
 0.8034398  0.81541769 0.81142506 0.82002457]

In [20]:
# soft voting classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
log_clf = LogisticRegression(solver='lbfgs')
rnd_clf = RandomForestClassifier(n_estimators=100)
svm_clf = SVC(gamma='scale', probability=True)
voting_clf = VotingClassifier(
    estimators=[('lr', log_clf), ('rf', rnd_clf), ('svc', svm_clf)],
    voting='soft')

In [ ]:
# measure the algorithm performance using 10-fold cross validation
from sklearn.model_selection import cross_val_score
for clf in (log_clf, rnd_clf, svm_clf, voting_clf):
    soft_voting_score = cross_val_score(voting_clf, X, y, scoring = 'accuracy', cv=10)
    print(clf.__class__.__name__, soft_voting_score.mean())

In [ ]:
# there is not much difference between the accuracy score of hard voting and soft voting

In [22]:
# Question 2:
# decision tree clasifier to use in bagging
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
bag_clf = BaggingClassifier(
    DecisionTreeClassifier(), n_estimators=100,
    max_samples=500, bootstrap=True, n_jobs=-1)

In [23]:
from sklearn.model_selection import cross_val_score
accuracy1 = cross_val_score(bag_clf, X, y, scoring = 'accuracy', cv=10)
accuracy1.mean()

0.8566691265608981

In [24]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
bag_clf = BaggingClassifier(
    DecisionTreeClassifier(), n_estimators=100,
    max_samples=500, bootstrap=True, max_features = 5, n_jobs=-1)

In [25]:
from sklearn.model_selection import cross_val_score
accuracy2 = cross_val_score(bag_clf, X, y, scoring = 'accuracy', cv=10)
accuracy2.mean()

0.7591904489970196

In [ ]:
# the one trained on all features performs better than the other one trained with max_features set to 5

In [40]:
# question 3:
# using GradientBoostingClassifier
# n_estimators=200, learning_rate=0.25
from sklearn.ensemble import GradientBoostingRegressor
gbrt = GradientBoostingRegressor(max_depth=2, n_estimators=200, learning_rate=0.25)
gbrt.fit(X, y)
gbrt.score(X,y)

0.5060635111778968

In [41]:
# n_estimators=500, learning_rate=0.5
from sklearn.ensemble import GradientBoostingRegressor
gbrt = GradientBoostingRegressor(max_depth=2, n_estimators=500, learning_rate=0.5)
gbrt.fit(X, y)
gbrt.score(X,y)

0.5529840651256653

In [42]:
# n_estimators=1000, learning_rate=1.0
from sklearn.ensemble import GradientBoostingRegressor
gbrt = GradientBoostingRegressor(max_depth=2, n_estimators=1000, learning_rate=1.0)
gbrt.fit(X, y)
gbrt.score(X,y)

0.6089625798885627

In [ ]:
# n_estimators=1000 and learning_rate=1.0 give the best performance boost